// Fixed advert fixtures keep regression checks independent of live editorial updates.
// Behaviour checks without browser dependencies.
const fs=require('fs'),vm=require('vm'),assert=require('assert'),path=require('path');
const root=path.resolve(__dirname,'..');
const context={console,URL,URLSearchParams,Intl,Date};vm.createContext(context);
const script=fs.readFileSync(path.join(root,'site/app.js'),'utf8').replace(/load\(\);\s*$/,'');
vm.runInContext(script+'\nglobalThis.logic={active,matches,renderCard,formatDeadline,advertCaveats,reportURL,safeURL,initTheme,paginate,render,filtersChanged,restore,reset,changePage,collectionSummary,sourceCheckSummary,renderSources,renderHealth,setData:value=>{database=value},setSourceData:value=>{sourceData=value},setHealth:value=>{healthData=value},setPage:value=>{currentPage=value},getPage:()=>currentPage};',context);
const {active,matches,renderCard,safeURL}=context.logic;
const allItems=JSON.parse(fs.readFileSync(path.join(root,'tests/fixtures/opportunities.json'),'utf8')).opportunities;
const initialIds=['lincoln-pest-networks-2026','hutton-peatlands-pollinators-2026','leeds-black-soldier-fly-b12-2026','nhm-dissco-digitiser-2026','rspb-woodland-scientist-2026','butterfly-grassland-officer-2026','wildfish-smartrivers-analysts','monteverde-insect-internship','beewalk-volunteer','kcl-fly-facility-technician-2026'];
const items=allItems.filter(x=>initialIds.includes(x.id));
const now=Date.parse('2026-09-29T15:30:00Z');
const state={q:'',types:[],subject:'',location:'uk',source:'',closing:false,sort:'deadline'};
assert.equal(items.filter(x=>matches(x,state,now)).length,9);
assert.equal(items.filter(x=>matches(x,{...state,types:['phd']},now)).length,3);
assert(matches(items.find(x=>x.id==='lincoln-pest-networks-2026'),{...state,q:'integrated pest management'},now));
assert.equal(items.filter(x=>matches(x,{...state,subject:'Crop protection & IPM'},now)).length,1);
assert.equal(items.filter(x=>matches(x,{...state,types:['mres']},now)).length,0);
assert.equal(items.filter(x=>matches(x,{...state,location:'international'},now)).length,1);
assert.equal(items.filter(x=>matches(x,{...state,closing:true},now)).length,5);
const internship=items.find(x=>x.type==='internship');
assert(matches(internship,{...state,location:'all',types:['volunteering']},now));
const lincoln=items.find(x=>x.id==='lincoln-pest-networks-2026');
assert(active(lincoln,Date.parse('2026-10-16T10:59:00Z')));
assert(!active(lincoln,Date.parse('2026-10-16T11:00:00Z')));
assert.equal(items.filter(x=>active(x,Date.parse('2026-10-30T15:30:00Z'))).length,0);
assert.equal(safeURL('javascript:alert(1)'),'#');
const hostile={...lincoln,title:'<img src=x onerror=alert(1)>',url:'javascript:alert(1)'};
const html=renderCard(hostile,now);assert(!html.includes('<img'));assert(!html.includes('href="javascript:'));
const report=new URL(context.logic.reportURL({...lincoln,title:'Insects & ecology? / #1'}));
assert.equal(report.protocol,'https:');assert.equal(report.hostname,'github.com');assert.equal(report.pathname,'/entomology-hau/career_opportunities/issues/new');
assert.equal(report.searchParams.get('title'),'[Advert report] Insects & ecology? / #1');
assert.equal(report.searchParams.get('body'),`Advert ID: ${lincoln.id}\nAdvert URL: ${lincoln.url}\n\nReason (tick one):\n- [ ] Irrelevant\n- [ ] Closed/expired\n- [ ] Incorrect details\n- [ ] Other\n\nDetails:\n`);
const queryURL='https://example.org/advert?type=job&ref=board';assert(new URL(context.logic.reportURL({...lincoln,url:queryURL})).searchParams.get('body').includes('Advert URL: '+queryURL+'\n'));assert(renderCard({...lincoln,url:queryURL},now).includes('href="https://example.org/advert?type=job&amp;ref=board"'));
const hostileReport=new URL(context.logic.reportURL({...hostile,id:'one\ntwo'}));
assert.match(hostileReport.searchParams.get('body'),/^Advert ID: one two\nAdvert URL: #\n/);assert.equal(hostileReport.searchParams.get('title'),'[Advert report] '+hostile.title);
assert.match(html,/Report advert/);assert.match(html,/GitHub sign-in required/);assert(!html.includes('href="https://github.com/entomology-hau/career_opportunities/issues/new?title=[Advert'));
const automatic={id:'auto-ecology',title:'Biodiversity research opportunity',url:'https://example.org/advert?id=1',source:'Official feed',sourceId:'feed',type:'other',reviewStatus:'automatic',status:'open',lastChecked:null,firstSeen:'2026-09-27',lastSeen:'2026-09-29',deadline:null,deadlineAt:null,deadlineLabel:null,organisation:null,location:null,country:null,workplace:null,compensation:null,eligibility:null,summary:'A source summary.',classificationInferred:true,courses:['biological-recording'],subjects:['Ecology & biodiversity'],tags:['Biodiversity']};
assert(active(automatic,now));assert(!active({...automatic,lastSeen:'2026-08-01'},now));assert(!active({...automatic,lastSeen:null},now));
assert(!active({...automatic,status:'expired'},now));assert(!active({...automatic,status:'closed'},now));assert(!active({...automatic,deadlineAt:'2026-09-29T12:00:00Z'},now));
assert(matches(automatic,{...state,types:['other']},now));assert(!matches(automatic,{...state,location:'international'},now));
assert(matches({...automatic,country:'France',location:'Paris'},{...state,location:'international'},now));assert(!matches({...automatic,country:'France'},{...state,location:'uk'},now));
assert(active({...lincoln,lastChecked:'2026-08-01',lastSeen:'2026-09-29'},now));
const automaticHTML=renderCard(automatic,now);
assert.match(automaticHTML,/Automatic source match/);assert.match(automaticHTML,/Other opportunity/);assert.match(automaticHTML,/Collected 27 September 2026/);assert.match(automaticHTML,/Listed at source 29 September 2026/);
assert(!automaticHTML.includes('Reviewed '));assert.match(automaticHTML,/Location not supplied — check advert/);assert.match(automaticHTML,/>Source details</);assert.match(automaticHTML,/Type inferred from source/);assert(!automaticHTML.includes('class="funding-line"'));assert(!automaticHTML.includes('<dt>Eligibility</dt>'));
// Caveats identify absent details without declaring supplied fields missing.
const caveats=item=>Array.from(context.logic.advertCaveats(item));
assert.deepEqual(caveats(automatic),['closing date','location','employer / organisation','eligibility','opportunity type']);
assert.match(automaticHTML,/<strong>Check main advert for<\/strong> closing date, location, employer \/ organisation, eligibility and opportunity type/);
const complete={...automatic,type:'job',organisation:'Field Research Institute',location:'Shropshire',country:'United Kingdom',compensation:'£30,000 per annum',eligibility:'Relevant degree and right to work in the UK.',deadline:'2026-10-16',deadlineAt:'2026-10-16T16:00:00Z',deadlineLabel:'16 October 2026',relevanceTier:'Core subject'};
// One formatter uses the calendar date and explicitly stated clock, never a synthetic cutoff.
const deadlineFormat=item=>context.logic.formatDeadline(item,now);
const dateOnly={...complete,deadline:'2026-10-04',deadlineTime:null,deadlineAt:'2026-10-05T00:00:00+01:00'};
assert.equal(deadlineFormat({...dateOnly,reviewStatus:'automatic',deadlineLabel:'2026-10-04'}),'4 October 2026');
assert.equal(deadlineFormat({...dateOnly,reviewStatus:'approved',deadlineLabel:'4 October 2026'}),'4 October 2026');
assert.equal(deadlineFormat({...dateOnly,deadlineLabel:'2026-10-04 · source date; confirm closing time'}),'4 October 2026 · source date; confirm closing time');
assert.equal(deadlineFormat(lincoln),'16 October 2026, 12:00 UK time');
assert.equal(deadlineFormat({...dateOnly,deadlineTime:'23:59',deadlineLabel:'4 October 2026, 23:59 CET; may close early'}),'4 October 2026, 23:59 CET; may close early');
assert.equal(deadlineFormat({...dateOnly,deadlineLabel:'4 October 2026; may close early'}),'4 October 2026 · may close early');
const formattedCard=renderCard({...dateOnly,deadlineLabel:'2026-10-04',notes:'The employer may close the advert early.'},now);
assert.match(formattedCard,/>4 October 2026<\/span>/);assert.match(formattedCard,/<dt>Deadline<\/dt><dd>4 October 2026<\/dd>/);assert.match(formattedCard,/The employer may close the advert early/);assert(!formattedCard.includes('5 October 2026'));assert(!formattedCard.includes('00:00'));
const closesToday={...dateOnly,deadline:'2026-09-29',deadlineTime:'12:00',deadlineLabel:'29 September 2026, 12 noon'};
assert.equal(deadlineFormat(closesToday),'29 September 2026, 12:00 · closes today');
assert.equal(deadlineFormat({...automatic,deadlineLabel:'Ongoing registration; surveys March–October'}),'Ongoing registration; surveys March–October');
assert.equal(deadlineFormat({...automatic,deadlineLabel:'Year-round openings'}),'Year-round openings');
assert.deepEqual(caveats(complete),[]);assert(!renderCard(complete,now).includes('class="advert-caveat"'));
const missingFields={...complete,deadline:null,deadlineAt:null,deadlineLabel:'Closing date not supplied',location:'Location not supplied',country:'Country not supplied',organisation:'Organisation not supplied',compensation:'Salary not stated in the checked advert',eligibility:'Eligibility not supplied'};
assert.deepEqual(caveats(missingFields),['closing date','location','employer / organisation','salary','eligibility']);
assert(matches(missingFields,{...state,types:['job']},now));assert(!matches(missingFields,{...state,location:'international'},now));
assert.deepEqual(caveats({...complete,type:'phd',compensation:null}),['funding / fees']);
assert.deepEqual(caveats({...complete,type:'mres',compensation:'Funding not supplied'}),['funding / fees']);
assert.deepEqual(caveats({...complete,type:'internship',compensation:'Pay not disclosed'}),['pay']);
assert.deepEqual(caveats({...complete,type:'volunteering',compensation:null}),[]);
assert.deepEqual(caveats({...complete,type:'internship',compensation:'Unpaid placement; no programme fee'}),[]);
assert.deepEqual(caveats({...complete,type:'phd',compensation:'Tuition fees and £21,805 annual stipend'}),[]);
assert.deepEqual(caveats({...complete,compensation:null,salary:'£30,000 per annum'}),[]);
assert.deepEqual(caveats({...complete,location:null,workplace:'Remote',country:null}),[]);
assert.deepEqual(caveats({...complete,relevanceTier:'Related field'}),['relevance to your interests']);
assert.deepEqual(caveats({...complete,reviewStatus:'approved',relevanceTier:'Related field'}),[]);
// Explicitly missing parts receive specific prompts; known ongoing schemes retain their stated availability.
assert.deepEqual(caveats({...complete,compensation:'Competitive salary (amount not stated), company vehicle and ongoing training'}),['salary amount']);
assert.deepEqual(caveats({...complete,compensation:'Competitive day or per-sample rates; amount not stated'}),['pay rate']);
assert.deepEqual(caveats({...complete,type:'phd',compensation:'3.5-year funded studentship; stipend amount not stated on checked advert'}),['stipend amount']);
assert.deepEqual(caveats({...complete,type:'phd',compensation:'Funded PhD; financial amount not stated on the checked project advert'}),['funding amount']);
assert.deepEqual(caveats({...complete,eligibility:'Relevant degree and driving licence required. Visa sponsorship is not stated.'}),['visa sponsorship']);
assert.deepEqual(caveats({...complete,eligibility:'No qualifications required. Visa eligibility is not stated.'}),['visa eligibility']);
assert.deepEqual(caveats({...complete,eligibility:'Relevant degree required. No visa sponsorship.'}),[]);
assert.deepEqual(caveats({...complete,type:'volunteering',compensation:null,deadline:null,deadlineAt:null,deadlineLabel:'Ongoing registration; surveys March–October'}),['current availability']);
const hostileFields={...missingFields,title:'<img src=x onerror=alert(1)>',location:'<script>alert(1)</script>',organisation:'<iframe src=x>',compensation:'<img src=x>',eligibility:'<script>',deadlineLabel:'<svg onload=alert(1)>',fitReason:'<img src=x>'};
const hostileFieldsHTML=renderCard(hostileFields,now);for(const tag of ['<img','<script','<iframe','<svg'])assert(!hostileFieldsHTML.includes(tag));assert(hostileFieldsHTML.includes('&lt;script&gt;'));
const related=allItems.find(x=>x.id==='crg-mountain-lakes-edna-2027');
assert(matches(related,{...state,location:'all',q:'biodiversity',relevance:'Related field'},now));
assert(!matches(related,{...state,relevance:'Core subject'},now));
const pba=allItems.find(x=>x.id==='pba-graduate-assistant-ecologist-2026');
assert(matches(pba,{...state,course:'biological-recording',relevance:'Core subject'},now));
assert(!matches(pba,{...state,course:'ipm'},now));
assert(matches(pba,{...state,q:'biological recording'},now));
assert(!matches(lincoln,{...state,course:'biological-recording'},now));
const advisor=allItems.find(x=>x.id==='morepeople-horticulture-ipm-advisor-2026');
assert(matches(advisor,{...state,q:'integrated pest management',relevance:'Core subject'},now));
const sequence=Array.from({length:61},(_,i)=>i);
for(const size of [10,20,30,40,50]){
  const pages=Math.ceil(sequence.length/size),seen=[];
  for(let i=1;i<=pages;i++){
    const page=context.logic.paginate(sequence,i,size);
    assert.equal(page.page,i);assert.equal(page.pages,pages);assert(page.items.length<=size);
    assert.equal(page.start,(i-1)*size+1);assert.equal(page.end,Math.min(i*size,61));seen.push(...page.items);
  }
  assert.deepEqual(seen,sequence);
}
assert.equal(context.logic.paginate(sequence,999,10).page,7);
for(const invalid of [-1,0,1.5,Infinity,'oops'])assert.equal(context.logic.paginate(sequence,invalid,10).page,1);
assert.equal(context.logic.paginate(sequence,1,7).pageSize,10);
const empty=context.logic.paginate([],9,10);assert.equal(empty.page,1);assert.equal(empty.start,0);assert.equal(empty.end,0);
// Exercise the actual render/filter/URL wiring with a small DOM stub.
const elements={};
const element=id=>elements[id]||=({value:'',checked:false,hidden:false,disabled:false,innerHTML:'',textContent:'',options:[],classList:{toggle(){}},focus(){},scrollIntoView(){}});
context.document={getElementById:element,querySelectorAll:()=>[]};
context.Date=class extends Date{static now(){return now;}};
let savedURL='';context.history={replaceState:(_state,_title,url)=>{savedURL=url}};
context.location={pathname:'/board/',search:'',hash:''};
element('location').value='all';element('sort').value='deadline';element('page-size').value='10';
context.logic.setData({opportunities:allItems});context.logic.setPage(2);context.logic.render();
assert.equal((element('cards').innerHTML.match(/<article /g)||[]).length,10);
assert.equal(element('page-info').textContent,'Page 2 of 3');assert(savedURL.includes('page=2'));
element('course').value='biological-recording';context.logic.filtersChanged();
assert.equal(context.logic.getPage(),1);assert.equal(element('previous-page').disabled,true);assert(savedURL.includes('course=biological-recording'));
element('page-size').value='50';context.logic.filtersChanged();assert.equal(element('pagination').hidden,true);
assert.equal((element('cards').innerHTML.match(/<article /g)||[]).length,13);
element('search').value='no-such-opportunity';context.logic.filtersChanged();assert.equal(element('empty').hidden,false);assert.equal(element('cards').innerHTML,'');
context.logic.reset();assert.equal(element('course').value,'');assert.equal(element('search').value,'');assert.equal(context.logic.getPage(),1);
element('page-size').options=[10,20,30,40,50].map(value=>({value:String(value)}));element('course').options=[{value:'biological-recording'}];
context.location.search='?course=biological-recording&page-size=20&page=999';context.logic.restore();context.logic.render();
assert.equal(element('page-size').value,'20');assert.equal(context.logic.getPage(),1);assert.equal(element('pagination').hidden,true);
context.logic.setData({opportunities:[{...automatic,id:'auto-new',firstSeen:'2026-09-29'}, {...automatic,id:'auto-old',lastSeen:'2026-09-28'}, lincoln]});
element('course').value='';element('sort').value='newest';element('location').value='uk';context.logic.render();
assert.match(element('freshness').textContent,/Most recent collection: 29 September 2026/);assert.match(element('freshness').textContent,/Latest editorial review:/);assert.match(element('result-count').textContent,/UK or with location unspecified/);
const newIndex=element('cards').innerHTML.indexOf('data-id="auto-new"'),oldIndex=element('cards').innerHTML.indexOf('data-id="auto-old"');assert(newIndex>=0&&oldIndex>newIndex);
// Collection health is distinct from editorial freshness and makes missing coverage visible.
const collectorSources=[{id:'res',name:'RES',enabled:true,mode:'res-headings'}, {id:'feed',name:'Feed',enabled:true,mode:'rss'}, {id:'manual',name:'Manual',enabled:false,mode:'manual'}];
const freshHealth={lastRun:'2026-09-29T14:00:00Z',discoveryStatus:'ok',pendingCandidates:4,summary:'Checks completed.',sources:[{id:'res',status:'ok',lastAttempt:'2026-09-29T14:00:00Z',entriesFound:24},{id:'feed',status:'ok',lastAttempt:'2026-09-29T14:00:00Z',entriesFound:0}],links:[]};
const freshSummary=context.logic.collectionSummary(freshHealth,collectorSources,now);
assert.equal(freshSummary.warning,false);assert.match(freshSummary.text,/2 of 2 collectors working/);assert(!freshSummary.text.includes('await'));assert(!freshSummary.text.includes('review'));
const publicationSummary=context.logic.collectionSummary({...freshHealth,publicationMode:'automatic',autoPublished:30,newPublished:5},collectorSources,now);
assert.match(publicationSummary.text,/30 automatic listings on the board/);assert.match(publicationSummary.text,/5 new listings added this check/);assert(!publicationSummary.text.includes('await'));assert(!publicationSummary.text.includes('editorial review'));
const hybridSummary=context.logic.collectionSummary({...freshHealth,publicationMode:'hybrid',autoPublished:30,newPublished:5},collectorSources,now);
assert.match(hybridSummary.text,/30 automatic listings on the board/);assert(!hybridSummary.text.includes('review'));assert(!hybridSummary.text.includes('closer relevance check'));
const partialHealth={...freshHealth,discoveryStatus:'partial',sources:[freshHealth.sources[0],{id:'feed',status:'unavailable',lastAttempt:freshHealth.lastRun}]};
const partialSummary=context.logic.collectionSummary(partialHealth,collectorSources,now);
assert.equal(partialSummary.warning,true);assert.match(partialSummary.text,/1 of 2 collectors working/);assert.match(partialSummary.text,/Some sources could not be collected/);
const failedSummary=context.logic.collectionSummary({...partialHealth,sources:[]},collectorSources,now);
assert.equal(failedSummary.warning,true);assert.match(failedSummary.text,/Automatic discovery is unavailable/);
const staleSummary=context.logic.collectionSummary(freshHealth,collectorSources,now+3*86400000);
assert.equal(staleSummary.warning,true);assert.match(staleSummary.text,/over 48 hours old/);
assert.equal(context.logic.collectionSummary(null,collectorSources,now).warning,true);
assert.match(context.logic.collectionSummary({lastRun:'bad'},collectorSources,now).text,/status is unavailable/);
assert.match(context.logic.sourceCheckSummary(collectorSources[2],null,now).text,/Assisted search/);
assert.equal(context.logic.sourceCheckSummary(collectorSources[2],null,now).warning,false);
assert.match(context.logic.sourceCheckSummary(collectorSources[1],freshHealth,now).text,/Automated feed · 0 entries checked/);
assert.match(context.logic.sourceCheckSummary(collectorSources[0],freshHealth,now).text,/Automated index · 24 entries checked/);
assert.equal(context.logic.sourceCheckSummary(collectorSources[1],partialHealth,now).warning,true);
assert.match(context.logic.sourceCheckSummary(collectorSources[1],null,now).text,/awaiting a source check/);
assert.equal(context.logic.sourceCheckSummary(collectorSources[0],freshHealth,now+3*86400000).warning,true);
context.logic.setSourceData({sources:collectorSources.map(s=>({...s,description:'<img src=x>',label:'Source label',url:'https://example.org'})),keywordGroups:[]});
context.logic.setHealth(freshHealth);context.logic.renderHealth(now);context.logic.renderSources();
assert.equal(element('collection-summary').textContent,freshSummary.text);
assert.match(element('source-cards').innerHTML,/Assisted search/);assert(!element('source-cards').innerHTML.includes('<img'));
assert.match(element('check-status').textContent,/Editorial review dates remain separate/);
context.logic.setHealth({...freshHealth,summary:'4 candidates awaiting admin review.'});context.logic.renderHealth(now);assert(!element('check-status').textContent.includes('awaiting'));assert(!element('check-status').textContent.includes('admin review'));
const publicPage=fs.readFileSync(path.join(root,'site/index.html'),'utf8');assert(!publicPage.includes('href="admin.html"'));assert(!/owner review|wait for review/i.test(publicPage));assert(publicPage.includes('Curated for the Applied Ecology postgraduate community. Follow each advert for full details, eligibility and how to apply. Double check the adverts origin for up-to-date details.'));
const reviewDate=lincoln.lastChecked;
context.logic.setHealth({...freshHealth,links:[{id:lincoln.id,status:'reachable',contentChanged:true}]});
assert.match(renderCard(lincoln,now),/Source page changed.*confirm the current details/);assert.equal(lincoln.lastChecked,reviewDate);
context.logic.setHealth({...freshHealth,links:[{id:lincoln.id,status:'needs-check'}]});
assert.match(renderCard(lincoln,now),/Link needs checking/);assert.equal(lincoln.lastChecked,reviewDate);
let saved=null,clickHandler,pressed;
context.localStorage={getItem:()=>saved,setItem:(_key,value)=>{saved=value}};
const rootElement={dataset:{theme:'dark'}},meta={content:''};
context.document={documentElement:rootElement,getElementById:()=>({setAttribute:(_key,value)=>{pressed=value},addEventListener:(_event,handler)=>{clickHandler=handler}}),querySelector:()=>meta};
context.logic.initTheme();assert.equal(rootElement.dataset.theme,'light');assert.equal(pressed,'false');
clickHandler();assert.equal(rootElement.dataset.theme,'dark');assert.equal(saved,'dark');assert.equal(pressed,'true');
context.logic.initTheme();assert.equal(rootElement.dataset.theme,'dark');
clickHandler();assert.equal(rootElement.dataset.theme,'light');assert.equal(saved,'light');
context.localStorage={getItem:()=>{throw Error('Storage disabled')},setItem:()=>{throw Error('Storage disabled')}};
context.logic.initTheme();clickHandler();assert.equal(rootElement.dataset.theme,'dark');
console.log('PASS: filters/dates; automatic and reviewed records; field-specific caveats and explicit missing parts; supplied-field preservation; report URLs; pagination; publication counts; safe rendering; separate source/editorial dates; themes.');
